Repository canonical/kserve-operators, pull requests merged in 2023-09, with the labels that each got.

#163 fix: redesign default images handling
  charms/kserve-controller/src/charm.py
  charms/kserve-controller/src/default-custom-images.json
Labels: Libraries: OK

#164 fix: get images on main
  tools/get-images.sh
Labels: Libraries: OK

#166 remove incomplete kserve-web-app (#147)
  .github/workflows/get-charm-paths.sh
  .github/workflows/integrate.yaml
  charms/kserve-web-app/.github/ISSUE_TEMPLATE/bug_report.yml
  charms/kserve-web-app/.github/ISSUE_TEMPLATE/enhancement_proposal.yml
  charms/kserve-web-app/.github/workflows/ci.yaml
  charms/kserve-web-app/.github/workflows/on_pull_request.yaml
  charms/kserve-web-app/.github/workflows/on_push.yaml
  charms/kserve-web-app/.gitignore
  charms/kserve-web-app/.jujuignore
  charms/kserve-web-app/LICENSE
  charms/kserve-web-app/README.md
  charms/kserve-web-app/charmcraft.yaml
  charms/kserve-web-app/config.yaml
  charms/kserve-web-app/metadata.yaml
  charms/kserve-web-app/pyproject.toml
  charms/kserve-web-app/requirements-fmt.in
  charms/kserve-web-app/requirements-fmt.txt
  charms/kserve-web-app/requirements-integration.in
  charms/kserve-web-app/requirements-integration.txt
  charms/kserve-web-app/requirements-lint.in
  charms/kserve-web-app/requirements-lint.txt
  charms/kserve-web-app/requirements-unit.in
  charms/kserve-web-app/requirements-unit.txt
  charms/kserve-web-app/requirements.in
  charms/kserve-web-app/requirements.txt
  charms/kserve-web-app/src/charm.py
  charms/kserve-web-app/tests/integration/test_charm.py
  charms/kserve-web-app/tests/unit/test_charm.py
  charms/kserve-web-app/tox.ini
  tox.ini
Labels: Libraries: Out of sync, backport

#169 ci: update juju to 3.1 and microk8s to 1.25
  .github/workflows/integrate.yaml
  charms/kserve-controller/requirements-integration.in
  charms/kserve-controller/requirements-integration.txt
  charms/kserve-controller/tests/integration/test_charm.py
  charms/kserve-controller/tox.ini
Labels: Libraries: OK

#170 Kf 4326 feat integrate mlserver for 1.7
  charms/kserve-controller/src/templates/serving_runtimes_manifests.yaml.j2
  charms/kserve-controller/tests/integration/mlserver-sklearn-iris.yaml
  charms/kserve-controller/tests/integration/test_charm.py
Labels: Libraries: Out of sync

#175 bump version 0.10.0 -> 0.11.0 for CKF release 1.8
  .gitignore
  README.md
  charms/kserve-controller/config.yaml
  charms/kserve-controller/metadata.yaml
  charms/kserve-controller/src/charm.py
  charms/kserve-controller/src/default-custom-images.json
  charms/kserve-controller/src/templates/auth_manifests.yaml.j2
  charms/kserve-controller/src/templates/configmap_manifests.yaml.j2
  charms/kserve-controller/src/templates/crd_manifests.yaml.j2
  charms/kserve-controller/src/templates/webhook_manifests.yaml.j2
  charms/kserve-controller/tests/integration/config-map-data-changed.yaml
  charms/kserve-controller/tests/integration/config-map-data.yaml
  charms/kserve-controller/tests/integration/test_charm.py
  charms/kserve-controller/tox.ini
Labels: Libraries: OK

#178 Run kserve-controller in serverless mode by default
  charms/kserve-controller/config.yaml
  charms/kserve-controller/tests/integration/test_charm.py
Labels: Libraries: OK

#181 remove kubeconfig file
  charms/kserve-controller/kubeconfig.tmp
Labels: Libraries: OK

#180 Kf 4436 backport airgap support
  .github/workflows/integrate.yaml
  README.md
  charms/kserve-controller/config.yaml
  charms/kserve-controller/lib/charms/istio_pilot/v0/istio_gateway_info.py
  charms/kserve-controller/src/charm.py
  charms/kserve-controller/src/default-custom-images.json
  charms/kserve-controller/src/templates/configmap_manifests.yaml.j2
  charms/kserve-controller/src/templates/serving_runtimes_manifests.yaml.j2
  charms/kserve-controller/tests/integration/test_charm.py
  charms/kserve-controller/tox.ini
  tools/get-images.sh
  tox.ini
Labels: Libraries: Out of sync
