Repository canonical/kserve-operators, pull requests merged in 2024-07, with the labels that each got.

#246 cherry-pick(fix): use an all-catch event handler (#197)
  charms/kserve-controller/src/charm.py
  charms/kserve-controller/tests/integration/test_charm.py
  charms/kserve-controller/tests/unit/test_charm.py
Labels: Libraries: OK

#251 ci: bump upload-charm action 2.4.0 -> 2.6.2
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#250 Add logging relation to kserve-controller
  charms/kserve-controller/lib/charms/loki_k8s/v1/loki_push_api.py
  charms/kserve-controller/metadata.yaml
  charms/kserve-controller/requirements-integration.in
  charms/kserve-controller/requirements-integration.txt
  charms/kserve-controller/requirements-unit.txt
  charms/kserve-controller/requirements.in
  charms/kserve-controller/requirements.txt
  charms/kserve-controller/src/charm.py
  charms/kserve-controller/tests/integration/test_charm.py
  charms/kserve-controller/tests/unit/test_charm.py
Labels: enhancement, Libraries: Out of sync

#253 ci(track): bump upload-charm action 2.4.0 -> 2.6.2
  .github/workflows/publish.yaml
Labels: Libraries: OK
