Repository canonical/kserve-operators, pull requests merged in 2024-08, with the labels that each got.

#258 ci(upload-charm): use charmcraft from latest/candidate
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#260 ci(upload-charm): use charmcraft from latest/candidate in track/0.13
  .github/workflows/publish.yaml
Labels: Libraries: Out of sync

#264 build: bump jinja2 3.1.x -> 3.1.4 (#256)
  charms/kserve-controller/requirements-unit.txt
  charms/kserve-controller/requirements.txt
Labels: Libraries: OK

#267 (cherry-pick to track/0.11) fix: configure proxy env vars storage init container (#257)
  charms/kserve-controller/config.yaml
  charms/kserve-controller/src/charm.py
  charms/kserve-controller/src/templates/cluster_storage_containers.yaml.j2
  charms/kserve-controller/tests/integration/test_charm.py
Labels: Libraries: OK

#265 Add alert rules to kserve-controller based on the KF093 spec
  charms/kserve-controller/src/prometheus_alert_rules/KubeflowKserveControllerServices.rules
  charms/kserve-controller/tests/integration/test_charm.py
Labels: Libraries: Out of sync

#268 (cherry-pick to track/0.13) fix: configure proxy env vars storage init container (#257)
  charms/kserve-controller/config.yaml
  charms/kserve-controller/src/charm.py
  charms/kserve-controller/src/templates/cluster_storage_containers.yaml.j2
  charms/kserve-controller/tests/integration/test_charm.py
Labels: Libraries: Out of sync

#266 chore(backport): Add metrics relation (#261)
  charms/kserve-controller/lib/charms/observability_libs/v1/kubernetes_service_patch.py
  charms/kserve-controller/lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  charms/kserve-controller/metadata.yaml
  charms/kserve-controller/src/charm.py
  charms/kserve-controller/src/templates/configmap_manifests.yaml.j2
  charms/kserve-controller/tests/integration/config-map-data-changed.yaml
  charms/kserve-controller/tests/integration/config-map-data.yaml
  charms/kserve-controller/tests/integration/test_charm.py
  charms/kserve-controller/tests/unit/test_charm.py
Labels: enhancement, Libraries: Out of sync

#259 ci(upload-charm): use charmcraft from latest/candidate in track/0.11
  .github/workflows/publish.yaml
Labels: Libraries: OK
